### ISSUE TITLE
uncalled functions in newton solver

### ISSUE THREAD

**Issue by IlsevanHerck** [ComputationalPhysiology/simcardems#118] opened 2022-12-05 17:26 UTC
These lines of code in the Newton solver seem to be unused. Using the Newton solver or custom Newton solver (and debug mode) does not use the function to create the file with residuals (residuals.txt). 
 https://github.com/ComputationalPhysiology/simcardems/blob/9ce6e1fe0ce0c654bdc63556d3cca00a66d41fda/src/simcardems/newton_solver.py#L82-L110

**Comment by finsberg** [comment] 2022-12-06 14:19
Duplicate of https://github.com/ComputationalPhysiology/simcardems/issues/115

**Closed** 2022-12-06 14:19 UTC
